#!/bin/sh
set -e

lb config noauto \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --debian-installer none \
    --memtest none \
    --bootappend-live "boot=live components username=aios" \
    --apt-recommends false \
    --debootstrap-options "--variant=minbase" \
    --linux-packages "linux-image" \
    --firmware-binary true \
    --firmware-chroot true \
    --iso-application "AIOS" \
    --iso-volume "AIOS Live" \
    "${@}"
